In [1]:
import pandas as pd
import geopandas as gpd

In [2]:
df = pd.read_csv("events.csv")
df["Address"] = df["Address"].str.replace("Madison", "; Madison").str.replace("Block ", "")
df

,Incident,Date,Incident Type,Address,Updated
0,"Fire Engulfs Shed Outside Eastside Restaurant,...",06/17/2020,Structure,"1700 Parkside Drive; Madison, WI",NaN
1,"Nobody Injured In Northside Fire, Cause Under ...",06/15/2020,Structure,"3700 E. Karstens Drive; Madison, WI",07/06/2020
2,Three Taken To Hospital Following Crash On Mil...,06/11/2020,Vehicle,"Milwaukee Street & Fair Oaks Avenue; Madison, WI",NaN
3,Two Rescued After Jet Ski Overturns On Lake Me...,06/08/2020,Lake Rescue,"Lake Mendota; Madison, WI",NaN
4,"Fire Damages Northside Apartment, Displaces Re...",06/06/2020,Structure,"3700 E. Karstens Drive; Madison, WI 53704",06/08/2020
...,...,...,...,...,...
135,Worker Injured After Hand Becomes Trapped In M...,02/18/2020,Special Rescue,"2200 Fordem Avenue; Madison, WI",NaN
136,Fire Displaces Seven From Downtown Building; N...,02/06/2020,Structure,"100 N. Franklin Street; Madison, WI",02/20/2020
137,Small Fire Discovered In Bathroom of Vacant Ap...,02/03/2020,Structure,"5900 Schroeder Road; Madison, WI",NaN
138,Flames On Roof Point To Fire In HVAC Unit,02/03/2020,Appliance,"800 Walsh Road; Madison, WI",NaN
139,Fire At West Side Spa the Result Of Spontaneou...,01/27/2020,Structure,"600 Grand Canyon Drive; Madison, WI",NaN

In [3]:
gpd.tools.geocode("1700 Parkside Drive; Madison, WI", provider='nominatim',
                  user_agent="cs320")

,geometry,address
0,POINT (-89.31531 43.12112),"1700, Parkside Drive, Madison, Dane County, Wi..."

In [4]:
geo = gpd.tools.geocode(df["Address"], provider='nominatim',
                        user_agent="cs320")
df["geometry"] = geo["geometry"]
df = gpd.GeoDataFrame(df)

In [5]:
df[["Incident", "Date", "geometry"]].to_file("events.shp")